Repository giranm/pd-live-react, pull requests merged in 2022-06, with the labels that each got.

#128 [Fix] Consistent row selection on table update
  cypress/integration/Search/search.spec.js
  src/components/IncidentTable/IncidentTableComponent.js
Labels: bug, fix

#129 [Fix] Global Search Radius
  package.json
  src/config/fuse-config.js
  src/mocks/incidents.test.js
  src/redux/incidents/sagas.test.js
  src/util/incidents.js
  yarn.lock
Labels: bug, fix

#132 [Change Request] Limit incidents returned from large query
  cypress/integration/Query/query.spec.js
  src/App.js
  src/components/ConfirmQueryModal/ConfirmQueryModalComponent.js
  src/components/ConfirmQueryModal/ConfirmQueryModalComponent.test.js
  src/components/IncidentActions/IncidentActionsComponent.js
  src/components/IncidentActions/subcomponents/SelectedIncidentsComponent.js
  src/components/IncidentActions/subcomponents/SelectedIncidentsComponent.test.js
  src/components/IncidentTable/IncidentTableComponent.js
  src/components/IncidentTable/subcomponents/QueryActiveComponent.js
  src/components/IncidentTable/subcomponents/QueryActiveComponent.test.js
  src/components/IncidentTable/subcomponents/QueryCancelledComponent.js
  src/components/IncidentTable/subcomponents/QueryCancelledComponent.test.js
  src/components/QuerySettings/QuerySettingsComponent.test.js
  src/config/constants.js
  src/redux/incidents/sagas.js
  src/redux/persistence/config.js
  src/redux/query_settings/actions.js
  src/redux/query_settings/reducers.js
  src/redux/query_settings/sagas.js
  src/redux/query_settings/sagas.test.js
  src/redux/rootSaga.js
  src/util/helpers.js
  src/util/helpers.test.js
Labels: task, fix, change request

#130 [Task] Add auth component
  jest.config.js
  package.json
  src/App.js
  src/components/Auth/AuthComponent.js
  src/components/Auth/AuthComponent.scss
  src/components/Auth/AuthComponent.test.js
  src/components/DisclaimerModal/DisclaimerModalComponent.js
  src/components/NavigationBar/NavigationBarComponent.js
  src/components/QuerySettings/QuerySettingsComponent.test.js
  src/components/UnauthorizedModal/UnauthorizedModalComponent.js
  src/mocks/pdoauth.js
  src/redux/incidents/sagas.test.js
  src/redux/query_settings/sagas.test.js
  src/redux/settings/sagas.test.js
  src/redux/users/sagas.test.js
  src/util/auth.js
  src/util/auth.test.js
  src/util/pd-api-wrapper.js
  src/util/pdoauth.js
  yarn.lock
Labels: task, fix, change request

#133 [Release] v0.1.0 beta.0
  README.md
  cypress/integration/Query/query.spec.js
  cypress/integration/Search/search.spec.js
  jest.config.js
  package.json
  src/App.js
  src/components/Auth/AuthComponent.js
  src/components/Auth/AuthComponent.scss
  src/components/Auth/AuthComponent.test.js
  src/components/ConfirmQueryModal/ConfirmQueryModalComponent.js
  src/components/ConfirmQueryModal/ConfirmQueryModalComponent.test.js
  src/components/DisclaimerModal/DisclaimerModalComponent.js
  src/components/IncidentActions/IncidentActionsComponent.js
  src/components/IncidentActions/subcomponents/SelectedIncidentsComponent.js
  src/components/IncidentActions/subcomponents/SelectedIncidentsComponent.test.js
  src/components/IncidentTable/IncidentTableComponent.js
  src/components/IncidentTable/subcomponents/QueryActiveComponent.js
  src/components/IncidentTable/subcomponents/QueryActiveComponent.test.js
  src/components/IncidentTable/subcomponents/QueryCancelledComponent.js
  src/components/IncidentTable/subcomponents/QueryCancelledComponent.test.js
  src/components/NavigationBar/NavigationBarComponent.js
  src/components/QuerySettings/QuerySettingsComponent.test.js
  src/components/UnauthorizedModal/UnauthorizedModalComponent.js
  src/config/constants.js
  src/config/fuse-config.js
  src/config/version.js
  src/mocks/incidents.test.js
  src/mocks/pdoauth.js
  src/redux/incidents/sagas.js
  src/redux/incidents/sagas.test.js
  src/redux/persistence/config.js
  src/redux/query_settings/actions.js
  src/redux/query_settings/reducers.js
  src/redux/query_settings/sagas.js
  src/redux/query_settings/sagas.test.js
  src/redux/rootSaga.js
  src/redux/settings/sagas.test.js
  src/redux/users/sagas.test.js
  src/util/auth.js
  src/util/auth.test.js
  src/util/helpers.js
  src/util/helpers.test.js
  src/util/incidents.js
  src/util/pd-api-wrapper.js
  src/util/pdoauth.js
  yarn.lock
Labels: release
